# Generated by Django 6.0.3 on 2026-04-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('women', 'Women'), ('kids', 'Kids')], default='women', max_length=20),
        ),
    ]
