# Generated by Django 6.0.3 on 2026-05-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Stock quantity available for this size'),
        ),
    ]
