# Generated by Django 4.2.30 on 2026-07-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_update_productsize_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offersale',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offers/'),
        ),
    ]
